tab completion
iconomy5legacy/iConomy pull request #37
Opened 2023-06-27 06:01 UTC by ewof

2023-06-27 13:22 UTC, LlmDl reviewed
There are lots of unneeded formatting changes what will have to be undone. Before you get into that let me look at this further to see if its worth redoing or if tab completion is part of the local branch I have already.

2023-06-27 16:42 UTC, LlmDl requested changes
I've merged the command refactor PR which did not add any tab completion.

You'll have to rebase this PR to account for the conflict in the iConomy class, and also remove the unneeded formatting diffs.

2023-06-27 19:03 UTC, LlmDl requested changes
I think I've done my changes now you just have to get the tab completion showing the right commands for the given context:

- true/false should only show when /money hide NAME is used.

- /money grant NAME AMOUNT should have a silent option offered on the end of it.

- nothing should be offered when a command has reached its limit tab completion, currently it will offer player names over and over.

- /money top should prompt an amount instead of a name.


I don't think I've spotted any other funky things.

2023-06-27 19:41 UTC, ewof commented
done

2023-06-27 22:19 UTC, LlmDl requested changes
Found the following issues still present.

- /money rank # continues to show a `amount` tab completion after #.
- /money top # continues to show a `amount` tab completion after #.
- /money hide name shows amount after name instead of true|false
- /money create name shows an amount after name.
- /money remove name shows an amount after name.
- /money reset name shows an amount after name.

2023-06-28 00:10 UTC, ewof commented
fixed

2023-07-04 13:35 UTC, LlmDl requested changes

2023-07-04 13:35 UTC, LlmDl commented on src/main/java/com/iConomy/MoneyCommand.java
> +				return Arrays.asList("true", "false");
This isn't correct, please test all of the tab completions against the help menu to confirm it is all correct, before I retest it.

2023-07-04 22:01 UTC, merged